#ifndef NECORE_INPUT_CONSTANTS_H_
#define NECORE_INPUT_CONSTANTS_H_

#include <GLFW/glfw3.h>

#define INPUT_JUST_INACTIVED -1
#define INPUT_INACTIVE 0
#define INPUT_JUST_ACTIVED 1
#define INPUT_ACTIVE 2

#define NC_KEY_UNKNOWN -1
/* Printable keys */
#define NC_KEY_SPACE              GLFW_KEY_SPACE
#define NC_KEY_APOSTROPHE         GLFW_KEY_APOSTROPHE
#define NC_KEY_COMMA              GLFW_KEY_COMMA
#define NC_KEY_MINUS              GLFW_KEY_MINUS
#define NC_KEY_PERIOD             GLFW_KEY_PERIOD
#define NC_KEY_SLASH              GLFW_KEY_SLASH
#define NC_KEY_0                  GLFW_KEY_0
#define NC_KEY_1                  GLFW_KEY_1
#define NC_KEY_2                  GLFW_KEY_2
#define NC_KEY_3                  GLFW_KEY_3
#define NC_KEY_4                  GLFW_KEY_4
#define NC_KEY_5                  GLFW_KEY_5
#define NC_KEY_6                  GLFW_KEY_6
#define NC_KEY_7                  GLFW_KEY_7
#define NC_KEY_8                  GLFW_KEY_8
#define NC_KEY_9                  GLFW_KEY_9
#define NC_KEY_SEMICOLON          GLFW_KEY_SEMICOLON
#define NC_KEY_EQUAL              GLFW_KEY_EQUAL
#define NC_KEY_A                  GLFW_KEY_A
#define NC_KEY_B                  GLFW_KEY_B
#define NC_KEY_C                  GLFW_KEY_C
#define NC_KEY_D                  GLFW_KEY_D
#define NC_KEY_E                  GLFW_KEY_E
#define NC_KEY_F                  GLFW_KEY_F
#define NC_KEY_G                  GLFW_KEY_G
#define NC_KEY_H                  GLFW_KEY_H
#define NC_KEY_I                  GLFW_KEY_I
#define NC_KEY_J                  GLFW_KEY_J
#define NC_KEY_K                  GLFW_KEY_K
#define NC_KEY_L                  GLFW_KEY_L
#define NC_KEY_M                  GLFW_KEY_M
#define NC_KEY_N                  GLFW_KEY_N
#define NC_KEY_O                  GLFW_KEY_O
#define NC_KEY_P                  GLFW_KEY_P
#define NC_KEY_Q                  GLFW_KEY_Q
#define NC_KEY_R                  GLFW_KEY_R
#define NC_KEY_S                  GLFW_KEY_S
#define NC_KEY_T                  GLFW_KEY_T
#define NC_KEY_U                  GLFW_KEY_U
#define NC_KEY_V                  GLFW_KEY_V
#define NC_KEY_W                  GLFW_KEY_W
#define NC_KEY_X                  GLFW_KEY_X
#define NC_KEY_Y                  GLFW_KEY_Y
#define NC_KEY_Z                  GLFW_KEY_Z
#define NC_KEY_LEFT_BRACKET       GLFW_KEY_LEFT_BRACKET
#define NC_KEY_BACKSLASH          GLFW_KEY_BACKSLASH
#define NC_KEY_RIGHT_BRACKET      GLFW_KEY_RIGHT_BRACKET
#define NC_KEY_GRAVE_ACCENT       GLFW_KEY_GRAVE_ACCENT
#define NC_KEY_WORLD_1            GLFW_KEY_WORLD_1
#define NC_KEY_WORLD_2            GLFW_KEY_WORLD_2

/* Function keys */
#define NC_KEY_ESCAPE             GLFW_KEY_ESCAPE
#define NC_KEY_ENTER              GLFW_KEY_ENTER
#define NC_KEY_TAB                GLFW_KEY_TAB
#define NC_KEY_BACKSPACE          GLFW_KEY_BACKSPACE
#define NC_KEY_INSERT             GLFW_KEY_INSERT
#define NC_KEY_DELETE             GLFW_KEY_DELETE
#define NC_KEY_RIGHT              GLFW_KEY_RIGHT
#define NC_KEY_LEFT               GLFW_KEY_LEFT
#define NC_KEY_DOWN               GLFW_KEY_DOWN
#define NC_KEY_UP                 GLFW_KEY_UP
#define NC_KEY_PAGE_UP            GLFW_KEY_PAGE_UP
#define NC_KEY_PAGE_DOWN          GLFW_KEY_PAGE_DOWN
#define NC_KEY_HOME               GLFW_KEY_HOME
#define NC_KEY_END                GLFW_KEY_END
#define NC_KEY_CAPS_LOCK          GLFW_KEY_CAPS_LOCK
#define NC_KEY_SCROLL_LOCK        GLFW_KEY_SCROLL_LOCK
#define NC_KEY_NUM_LOCK           GLFW_KEY_NUM_LOCK
#define NC_KEY_PRINT_SCREEN       GLFW_KEY_PRINT_SCREEN
#define NC_KEY_PAUSE              GLFW_KEY_PAUSE
#define NC_KEY_F1                 GLFW_KEY_F1
#define NC_KEY_F2                 GLFW_KEY_F2
#define NC_KEY_F3                 GLFW_KEY_F3
#define NC_KEY_F4                 GLFW_KEY_F4
#define NC_KEY_F5                 GLFW_KEY_F5
#define NC_KEY_F6                 GLFW_KEY_F6
#define NC_KEY_F7                 GLFW_KEY_F7
#define NC_KEY_F8                 GLFW_KEY_F8
#define NC_KEY_F9                 GLFW_KEY_F9
#define NC_KEY_F10                GLFW_KEY_F10
#define NC_KEY_F11                GLFW_KEY_F11
#define NC_KEY_F12                GLFW_KEY_F12
#define NC_KEY_F13                GLFW_KEY_F13
#define NC_KEY_F14                GLFW_KEY_F14
#define NC_KEY_F15                GLFW_KEY_F15
#define NC_KEY_F16                GLFW_KEY_F16
#define NC_KEY_F17                GLFW_KEY_F17
#define NC_KEY_F18                GLFW_KEY_F18
#define NC_KEY_F19                GLFW_KEY_F19
#define NC_KEY_F20                GLFW_KEY_F20
#define NC_KEY_F21                GLFW_KEY_F21
#define NC_KEY_F22                GLFW_KEY_F22
#define NC_KEY_F23                GLFW_KEY_F23
#define NC_KEY_F24                GLFW_KEY_F24
#define NC_KEY_F25                GLFW_KEY_F25
#define NC_KEY_KP_0               GLFW_KEY_KP_0
#define NC_KEY_KP_1               GLFW_KEY_KP_1
#define NC_KEY_KP_2               GLFW_KEY_KP_2
#define NC_KEY_KP_3               GLFW_KEY_KP_3
#define NC_KEY_KP_4               GLFW_KEY_KP_4
#define NC_KEY_KP_5               GLFW_KEY_KP_5
#define NC_KEY_KP_6               GLFW_KEY_KP_6
#define NC_KEY_KP_7               GLFW_KEY_KP_7
#define NC_KEY_KP_8               GLFW_KEY_KP_8
#define NC_KEY_KP_9               GLFW_KEY_KP_9
#define NC_KEY_DECIMAL         GLFW_KEY_DECIMAL
#define NC_KEY_DIVIDE          GLFW_KEY_DIVIDE
#define NC_KEY_MULTIPLY        GLFW_KEY_MULTIPLY
#define NC_KEY_SUBTRACT        GLFW_KEY_SUBTRACT
#define NC_KEY_ADD             GLFW_KEY_ADD
#define NC_KEY_ENTER           GLFW_KEY_ENTER
#define NC_KEY_EQUAL           GLFW_KEY_EQUAL
#define NC_KEY_LEFT_SHIFT         GLFW_KEY_LEFT_SHIFT
#define NC_KEY_LEFT_CONTROL       GLFW_KEY_LEFT_CONTROL
#define NC_KEY_LEFT_ALT           GLFW_KEY_LEFT_ALT
#define NC_KEY_LEFT_SUPER         GLFW_KEY_LEFT_SUPER
#define NC_KEY_RIGHT_SHIFT        GLFW_KEY_RIGHT_SHIFT
#define NC_KEY_RIGHT_CONTROL      GLFW_KEY_RIGHT_CONTROL
#define NC_KEY_RIGHT_ALT          GLFW_KEY_RIGHT_ALT
#define NC_KEY_RIGHT_SUPER        GLFW_KEY_RIGHT_SUPER
#define NC_KEY_MENU               GLFW_KEY_MENU

#define NC_MOUSE_BUTTON_1         GLFW_MOUSE_BUTTON_1
#define NC_MOUSE_BUTTON_2         GLFW_MOUSE_BUTTON_2
#define NC_MOUSE_BUTTON_3         GLFW_MOUSE_BUTTON_3
#define NC_MOUSE_BUTTON_4         GLFW_MOUSE_BUTTON_4
#define NC_MOUSE_BUTTON_5         GLFW_MOUSE_BUTTON_5
#define NC_MOUSE_BUTTON_6         GLFW_MOUSE_BUTTON_6
#define NC_MOUSE_BUTTON_7         GLFW_MOUSE_BUTTON_7
#define NC_MOUSE_BUTTON_8         GLFW_MOUSE_BUTTON_8
#define NC_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_LAST
#define NC_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_LEFT
#define NC_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_RIGHT
#define NC_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_MIDDLE

#endif /* NECORE_INPUT_CONSTANTS_H_ */
