#ifndef NECORE_VERSION_H_
#define NECORE_VERSION_H_

#define STRINGIFY(X) #X
#define STR(X) STRINGIFY(X)

#define NE_VERSION_MAJOR 0
#define NE_VERSION_MINOR 1
#define NE_VERSION_PATCH 0

#define NE_VERSION_STRING STR(NE_VERSION_MAJOR) "." STR(NE_VERSION_MINOR) "." STR(NE_VERSION_PATCH)

#define NE_BUILD_DATE __DATE__ " " __TIME__


#endif /* NECORE_VERSION_H_ */
